import {
  AlertTriangle,
  BarChart3,
  BookOpen,
  Bot,
  CheckCircle2,
  Circle,
  Database,
  FileText,
  LayoutTemplate,
  LoaderCircle,
  Menu,
  MoreHorizontal,
  Paperclip,
  Search,
  Send,
  Settings,
  Share2,
  Sparkles,
  Star,
  User,
  ChevronRight,
  Plus,
} from 'lucide-react';

export const icons = {
  brand: Bot,
  menu: Menu,
  plus: Plus,
  task: BarChart3,
  search: Search,
  database: Database,
  knowledge: BookOpen,
  document: FileText,
  chart: BarChart3,
  agent: Sparkles,
  alert: AlertTriangle,
  attachment: Paperclip,
  template: LayoutTemplate,
  send: Send,
  share: Share2,
  more: MoreHorizontal,
  user: User,
  settings: Settings,
  star: Star,
  chevronRight: ChevronRight,
  stepDone: CheckCircle2,
  stepCurrent: LoaderCircle,
  stepPending: Circle,
} as const;

export type IconKey = keyof typeof icons;
