import {
  Copy,
  AlertTriangle,
  BarChart3,
  BookOpen,
  Bot,
  CheckCircle2,
  Circle,
  Database,
  FileText,
  LayoutTemplate,
  LoaderCircle,
  Menu,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  Share2,
  Square,
  Sparkles,
  User,
  ChevronRight,
  Plus,
} from 'lucide-react';

export const icons = {
  brand: Bot,
  menu: Menu,
  plus: Plus,
  task: BarChart3,
  search: Search,
  database: Database,
  knowledge: BookOpen,
  document: FileText,
  chart: BarChart3,
  agent: Sparkles,
  alert: AlertTriangle,
  template: LayoutTemplate,
  send: Send,
  stop: Square,
  copy: Copy,
  regenerate: RefreshCw,
  retry: RotateCcw,
  report: FileText,
  share: Share2,
  user: User,
  settings: Settings,
  chevronRight: ChevronRight,
  stepDone: CheckCircle2,
  stepCurrent: LoaderCircle,
  stepPending: Circle,
} as const;

export type IconKey = keyof typeof icons;
